# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/2025Fall-UVA-CS-MachineLearningDeep/
url:            https://qiyanjun.github.io/

# Setup
title:            	"2025 Fall UVA CS - Machine Learning"
tagline:          	"2025 Fall"
description:        "TuTh 3:30pm-4:45PM"
future: 			true

author:
  name:           'Yanjun Qi'
  url:            https://qiyanjun.github.io/Homepage/


collections:
  contents:
    sort_by: LOrder
    output: true
